config/routes.rb
Rails.application.routes.draw do

  get '/translation' => 'i18n_admin_utils/translation#index', :as => :translation_home
  get 'translation/show' => 'i18n_admin_utils/translation#show', :as => :translation_missing_show
  get 'translation/list' => 'i18n_admin_utils/translation#missing_list', :as => :translation_missing_list
  get 'translation/list/element' => 'i18n_admin_utils/translation#list_element', :as => :translation_list_element
  post '/translation/edit' => 'i18n_admin_utils/translation#edit', :as => :translation_edit
end

app/controllers/i18n_admin_utils/application_controller.rb
module I18nAdminUtils
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
    layout 'i18n_admin_utils/application'
  end
end

app/controllers/i18n_admin_utils/translation_controller.rb
module I18nAdminUtils
  class TranslationController < ApplicationController
    def index
    end

    def edit
      if params[:key].nil?
        i18n_redirect('No key specified', false)
      else
        key = params[:key]
        locale = params[:locale]
        translation = params[:value]
        if locale.nil?
          if key.include? '.'
            split = key.split('.', 2)
            locale = split[0]
            key = split[1]
          else
            i18n_redirect('No locale specified', false)
            return
          end
        end
        I18nAdminUtils::Backend::Manager.save_translation(locale, key, translation)
        i18n_redirect('Translation edited with success')
      end
    end

    def show
      if params[:translation].nil?
        render :text => 'Error no params given'
      else
        translation = I18nAdminUtils::Translation.from_hash(params[:translation])
        if translation.key.nil?
          render :text => 'Error no key given'
        else
          render :partial => 'show', :locals => {:translation => translation}
        end
      end
    end

    #Return a list of all the missing translation
    def missing_list
      translations = I18nAdminUtils::SearchTranslation.search
      render :partial => 'missing_list', :layouts => false, :locals => {:translations => translations}
    end

    def list_element
      if params[:translation].nil?
        render :text => 'Error no translation given'
      else
        translation = I18nAdminUtils::Translation.from_hash(params[:translation])
        if translation.key.nil?
          render :text => 'Error no key given'
        else
          render :partial => 'list_element', :locals => {:translation => translation}
        end

      end
    end

    def i18n_redirect(message, success = true)
      if request.xhr?
        render :json => {:success => success, :message => message}
      else
        if success
          redirect_to :back, :notice => message
        else
          redirect_to :back, :alert => message
        end
      end
    end
  end
end

app/helpers/i18n_admin_utils/application_helper.rb
module I18nAdminUtils
  module ApplicationHelper

    #Show the number of translation missing with colorization
    def translation_missing_icon(translation)
      missing_translations = translation.missing_translations
      color_id = (missing_translations.size.to_f/translation.translations.size.to_f*5).ceil-1
      if missing_translations.size == 0
        content_tag 'span', '', :class => 'glyphicon glyphicon-ok greentext',
                    :title => 'This key has been translated in all languages', :rel => 'tooltip'
      else
        content_tag 'span', "(#{missing_translations.size})", :class => "color-range-#{color_id} bold",
                    :title => missing_translations.keys.join(','), :rel => 'tooltip'
      end
    end

    def translation_locations_compact_list(translation)
      if translation.locations.size == 0

        content_tag 'div', '', :class => 'translation_filename'
      elsif translation.locations.size == 1
        content_tag 'div', translation.locations.first[:filename].reverse, :class => 'translation_filename'
      else
        content = "#{translation.locations.first[:filename]} and #{translation.locations.size-1} more"
        title= translation.locations[1..-1].map { |x| "<div class='translation_filename'> #{x[:filename].reverse} </div>" }.join('')
        content_tag 'div', content.reverse, :class => 'translation_filename', :title => title, :rel => 'tooltip',
                    'data-html' => true
      end
    end
  end
end

app/views/i18n_admin_utils/translation/_list_element.html.erb
<div class="translation_item" data-translation='<%= translation.to_json %>' data-reload-url='<%= translation_list_element_path %>'
     data-key='<%= translation.key %>' data-completed='<%= not translation.missing_translation? %>'>
  <div class="row">
    <div class="col-md-1">
      <%= translation_missing_icon(translation) %>
    </div>
    <div class="col-md-5">
      <%= translation.key %>
    </div>
    <div class="col-md-6 ">
      <%= translation_locations_compact_list(translation) %>
    </div>
  </div>
</div>

app/views/i18n_admin_utils/translation/_missing_list.html.erb
<% translations.each do |translation| %>
    <%= render :partial => 'list_element', :locals => {:translation => translation} %>
<% end %>

app/views/i18n_admin_utils/translation/_show.html.erb
<% default_locale = I18nAdminUtils::Config.locales.first %>
<div class="row">
  <div class="col-md-12">
    <div class="btn-group">
      <% translation.translations.each do |locale, translation| %>
          <% type = translation.blank? ? 'danger' : 'success' %>
          <div class="btn btn-<%= type %> locale-tab <%= 'active' if locale == default_locale %>"
               data-translation='<%= translation %>' data-locale='<%= locale %>'>
            <%= locale %>
          </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row" style="margin-top: 2rem">
  <div class="col-md-6">
    <b>Key:</b> <%= translation.key %>
    <div>
      <%= form_tag translation_edit_path, :class => 'translation_form translation_helper' do %>
          <%= hidden_field_tag :locale, default_locale %>
          <%= hidden_field_tag :key, translation.key %>
          <%= text_area_tag :value, translation.translations[default_locale], :class => 'form-control autosize', 'data-update' => 'value_ta', :placeholder => 'Translate here...' %>
          <button class='btn btn-default'>
            Add
          </button>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="editor_container">
      <div>
        <% translation.locations.each do |location| %>
            <div class="location_container">
              <div>
                <i><%= location[:filename] %></i>
              </div>
              <div>
                <%= rails_embed_editor(location[:filename], :line => location[:line], :radius => 4,
                                       :editormode => RailsEmbedEditor::EditorMode::READ_WRITE,
                                       :highlight => location[:line]) %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/i18n_admin_utils/translation/index.html.erb
<div class="translation_title">
  <span class="text-lg text-bold">List translation key found in the application</span>
</div>

<div class="row translation_container">
  <div class="col-md-3 translation_list" data-url='<%= translation_missing_show_path %>' data-container='.translation_edit_container'>
    <div class="container-fluid translation_filter">
      <div class="row">
        <div class=" col-md-10">
          <%= text_field_tag :search, '', :class => 'translation_search form-control', :placeholder => 'Search...', :autocomplete => 'off' %>
        </div>
        <div class="col-md-2">
          <div class="btn btn-default active show-completed">
            <span class="glyphicon glyphicon-eye-open" title="Show completed" rel='tooltip'></span>
          </div>
        </div>
      </div>
    </div>
    <div class='loadonready' data-url='<%= translation_missing_list_path %>'>
    </div>
  </div>
  <div class='translation_edit_container col-md-9'>

  </div>
</div>

app/views/layouts/i18n_admin_utils/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/i18n_admin_utils/_navigation.html.erb
<div class=''>
  <ul ul class="nav navbar-nav">
    <li><%= link_to 'Home', '/', :class => 'brand' %></li>
    <li><%= link_to 'Missing translation', translation_home_path, :class => 'brand' %></li>
  </ul>
</div>

app/views/layouts/i18n_admin_utils/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'I18n Admin Utils' %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
  <%= stylesheet_link_tag 'i18n_admin_utils/application', :media => 'all' %>
  <%= javascript_include_tag 'i18n_admin_utils/application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'rails_embed_editor/application' %>
  <%= stylesheet_link_tag 'rails_embed_editor/application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class='navbar navbar-inverse navbar-fixed-top' role='navigation'>
  <%= render :partial => 'layouts/i18n_admin_utils/navigation' %>
</header>
<div class="wrapper container-fluid">
  <%= render :partial => 'layouts/i18n_admin_utils/messages' %>
  <%= yield %>
</div>

<div id='loading_icon' class="hidden">
  <div class="spinner"></div>
</div>
</body>
</html>